#!/bin/sh
xrdb $(i root)/util/Xresources 

#make user systemd scripts work with 
source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh
systemctl --user import-environment PATH

#export QT_AUTO_SCREEN_SCALE_FACTOR=1
#xrandr --dpi 144
#export QT_SCALE_FACTOR=1.26
systemctl --user import-environment QT_SCALE_FACTOR

xset -b off
xset r rate 300 50
setxkbmap -option caps:ctrl_modifier
wallpaper -l -r
wallpaper --set -c -r

source ~/.screenlayout/default.sh

#systemctl --user import-environment DISPLAY
systemctl --user start --wait xsession.target
#exec /usr/bin/i3
