"simple vimrc, complex config in dot/vim/.vimrc_extra
"author: Erich Spaker, Feb 2020
source ~/.vim/vimrc_extra

"disable vi compatibility mode
set nocompatible

"buffers
set hidden

"line endings
set fileformat=unix

"enable mouse
set mouse=a

"reduce timeouts to eliminate noticable delay
set ttimeoutlen=10 "escape delay
set timeoutlen=200 "mapping delay XXX when does this apply

"ensure arrow keys work in insert mode
set esckeys

"tab settings
set expandtab
set tabstop=4
set shiftwidth=4
set autoindent

"makefiles need tabs not spaces
autocmd FileType make setlocal noexpandtab

"hybrid line numbers
set number relativenumber

"enable status bar
set laststatus=2

"open split panes to the right/bottom
set splitright
set splitbelow

"search highlighting
set incsearch
set hlsearch

"clear search highlight on esc
nnoremap <esc><esc> :nohls <esc>

"syntax highlighting
syntax on
colorscheme jellybeans
set t_Co=256
highlight Normal ctermbg=Black
highlight NonText ctermbg=Black
let &t_ut=''
set background=dark

"persistent undo
set undodir=~/.vim/undo
set undofile

"backspace works like most editors in insert
set backspace=indent,eol,start

"space in normal mode
nnoremap <space> i<space><esc>

"enter: insert starting at end of line
nnoremap <silent> <CR> $a

"easier commands
vnoremap ; :
nnoremap ; :

"command to save with sudo
cnoreabbrev wsudo w !sudo tee % >/dev/null
