#!/bin/sh
xrdb /z/config/xorg.conf
xrdb-merge /z/config/urxvt.conf
xrdb-merge /z/config/colorscheme.conf

#make user systemd scripts work with 
source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh

#export QT_AUTO_SCREEN_SCALE_FACTOR=1
#xrandr --dpi 144
export QT_SCALE_FACTOR=1.4

xset -b off
wallpaper --set -c

systemctl --user start --wait xsession.target
#exec /usr/bin/i3
